### ISSUE TITLE
提2个小需求

### ISSUE THREAD

**Issue by jingyaogong** [the-seeds/imitater#8]
是否考虑把embedding模型和chat LLM放到同一个端口上（做成可选项）
```
chat:
  - name: gpt-3.5-turbo
    path: 
    device:
      - 1
    port: 8000

embed:
  - name: text-embedding-ada-002
    path: 
    device:
      - 1
    batchsize: 64
    port: 8001

service:
  host: 127.0.0.1
  port: 8002
```

openai在`https://api.openai.com/v1`下，同时具有`/embedding`和`/chat/xxx`接口

这个做法导致了据我所知的`web-chat`及`RAG`框架只有一个`Base_URL`可替换，而没法单独设置`LLM`和`embedding Model`的接口`URL`

当然，这个问题可以用端口转发例如nginx解决，以此统一服务地址。但调试略显不便。

此外，编码模型各显神通，中文刷榜的M3E-large英文能力欠佳，英文能力很强的BGE中文能力为0，但是希望它们同时被`/embedding`接口启用。我私下的`openai_api.py`中会判断句子中是否包含中文，是的话调用M3E编码，否则调用BGE。

因此提2个需求：

## 2、增加语言类型判断，动态选择合适的编码模型（小小建议，完全是因为当前没有openai那样的全能embedding模型）
